### PR TITLE
Update dependencies and ember-cli

### PR DESCRIPTION
**Pull request by btecu**
Remove `bower` usage.
Remove polyfill (use Ember's).
Use modules instead of global Ember.

### CODE REVIEW

**Comment by patience-tema-baron** [comment]
This PR is _incredibly_ welcome, but it looks like it's failing on Travis.

**Comment by btecu** [comment]
Had to update one of the packages used to not use `bower`: https://github.com/Robdel12/markdown-code-highlighting/pull/5

There is only one test, related to one of your other packages. Ideas why it's failing?

**Comment by patience-tema-baron** [comment]
Probably because of [this change](https://github.com/patience-tema-baron/ember-keyboard/pull/70/files#diff-b6ccd5920481257ff4e3594530ae2911L12). I'd say it's fine to go ahead and remove that test.

**Comment by btecu** [comment]
Makes sense. Pushed.

**Comment by patience-tema-baron** [comment]
Published under `v2.2.2`. Thanks for the pr, @btecu!

**Pull request merged**
